src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status = false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_livraison;

    /**
     * @ORM\OneToMany(targetEntity=DetailCommande::class, mappedBy="commande")
     */
    private $detailCommandes;

    public function __construct()
    {
        $this->detailCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(?\DateTimeInterface $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }

    /**
     * @return Collection|DetailCommande[]
     */
    public function getDetailCommandes(): Collection
    {
        return $this->detailCommandes;
    }

    public function addDetailCommande(DetailCommande $detailCommande): self
    {
        if (!$this->detailCommandes->contains($detailCommande)) {
            $this->detailCommandes[] = $detailCommande;
            $detailCommande->setCommande($this);
        }

        return $this;
    }

    public function removeDetailCommande(DetailCommande $detailCommande): self
    {
        if ($this->detailCommandes->removeElement($detailCommande)) {
            // set the owning side to null (unless already changed)
            if ($detailCommande->getCommande() === $this) {
                $detailCommande->setCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/DetailCommande.php
<?php

namespace App\Entity;

use App\Repository\DetailCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DetailCommandeRepository::class)
 */
class DetailCommande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="detailCommandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $commande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $article_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0, nullable=true)
     */
    private $tva;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): self
    {
        $this->commande = $commande;

        return $this;
    }

    public function getArticleName(): ?string
    {
        return $this->article_name;
    }

    public function setArticleName(string $article_name): self
    {
        $this->article_name = $article_name;

        return $this;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getTva(): ?string
    {
        return $this->tva;
    }

    public function setTva(?string $tva): self
    {
        $this->tva = $tva;

        return $this;
    }
}

src/Controller/Admin/CommandeController.php
<?php

namespace App\Controller\Admin;

use App\Classes\CommandeManager;
use App\Repository\CommandeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */

class CommandeController extends AbstractController
{
    /**
     * @Route("/commande/{livraison}", name="commande" , defaults={ "livraison" : false})
     */
    public function index($livraison,CommandeRepository $commandeRepository): Response
    {

        return $this->render('commande/commande.html.twig', [
            'commandes'=>$commandeRepository->findBy(['status'=> $livraison])
        ]);
    }


    /**
     * @Route("/commande-detail/{id}", name="voir_detail_commande")
     */
    public function voirDetailCommande($id,CommandeRepository $commandeRepository): Response
    { 
        // je récupére l'objet commande par son id passé dans l'url
        $commande=$commandeRepository->find($id);

        return $this->render('commande/detail_commande.html.twig', [
            'commande'=>$commande
        ]);
    }


     /**
     * @Route("/commande-modifier/{id}", name="edit_status_commande")
     */
    public function editStatus($id,CommandeRepository $commandeRepository,
                              CommandeManager $commandeManager): Response
    {
        // je récupére l'objet commande par son id passé dans l'url
        $commande=$commandeRepository->find($id);
        // je change le status de livraison avec la méthode editlivraisoncommande de la class commandemanager
        $commandeManager->editLivraisonCommande($commande);
        // je redirige sur la vue détail on passant lid dans l'url 
        return $this->redirectToRoute('voir_detail_commande',[ 'id' => $id]);


    
    }

}

templates/commande/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CommandeController!{% endblock %}

{% block body %}
<div class="container">
<h4 class="text-center">Liste des commande</h4>
<a href="{{ path('commande' , { 'livraison' : true }) }}" class="btn btn-primary">Commandes Livrées</a>
<a href="{{ path('commande' , { 'livraison' : false }) }}" class="btn btn-primary">Commandes Non livrées</a>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">User</th>
      <th scope="col">Date commande</th>
      <th scope="col">adresse</th>
      <th scope="col">Total</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  {% for article in commandes %}
    <tr>
      <th scope="row">{{ article.id }}</th>
      <td>{{ article.user.nom }}</td>
      <td>{{ article.datecommande.format('Y/m/d')  }}</td>
      <td>{{ article.adresse }}</td>
      <td>{{ article.total }}</td>
      <td>{{ article.status }}</td>

      <td><a class="btn mb-1 btn-primary" href="{{ path('voir_detail_commande' , { 'id' : article.id }) }}">Voir</a></td>
    </tr>
      
  {% endfor %}
    
   
  </tbody>
</table>
</div>

{% endblock %}

templates/commande/detail_commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CommandeController!{% endblock %}

{% block body %}
<div class="container">
<h4 class="text-center">Detail commande</h4>
 

 
 <p>num de commande :{{  commande.id }}</p>
 <p>Cliant : {{  commande.user.nom }} - {{ commande.user.prenom }}</p>
 <p> Date de la commande  : {{  commande.dateCommande.format('Y/m/d') }}</p>
 <p>Adresse de livraison : {{  commande.Adresse }}</p>
 <p>Total de la commande : {{  commande.total }}</p>

 {% if commande.status == true %}
     <p>Commande livrée</p>

     {% else %}
      <p>Commande non livrée</p>

 {% endif %}
  <td><a href="{{ path('edit_status_commande' , { 'id' : commande.id }) }}" class="btn btn-primary">Changer le status livraison</a></td>

 <hr>
 <h5>Article commandés</h5>
 <table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nom de L'article</th>
      <th scope="col">Référence</th>
      <th scope="col">Quantité</th>
      <th scope="col">Prix </th>
      
    </tr>
  </thead>
  <tbody>
  {% for article in commande.DetailCommandes %}
    <tr>
      <th scope="row">{{ article.id }}</th>
      <td>{{ article.articleName }}</td>
      <td>{{ article.ref  }}</td>
      <td>{{ article.quantity }}</td>
      <td>{{ article.Prix }}</td>
    
    
    </tr>
      
  {% endfor %}
    
   
  </tbody>
</table>

</div>


{% endblock %}