src/Entity/Tva.php
<?php

namespace App\Entity;

use App\Repository\TvaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TvaRepository::class)
 */
class Tva
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $taux_tva;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="tva")
     */
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTauxTva(): ?float
    {
        return $this->taux_tva;
    }

    public function setTauxTva(float $taux_tva): self
    {
        $this->taux_tva = $taux_tva;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setTva($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getTva() === $this) {
                $article->setTva(null);
            }
        }

        return $this;
    }
}

src/Form/TvaType.php
<?php

namespace App\Form;

use App\Entity\Tva;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TvaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('taux_tva')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tva::class,
        ]);
    }
}

src/Controller/Admin/TvaController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Tva;
use App\Form\TvaType;
use App\Repository\TvaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/tva")
 */
class TvaController extends AbstractController
{
    /**
     * @Route("/", name="tva_index", methods={"GET"})
     */
    public function index(TvaRepository $tvaRepository): Response
    {
        return $this->render('tva/index.html.twig', [
            'tvas' => $tvaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="tva_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tva = new Tva();
        $form = $this->createForm(TvaType::class, $tva);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tva);
            $entityManager->flush();

            return $this->redirectToRoute('tva_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tva/new.html.twig', [
            'tva' => $tva,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="tva_show", methods={"GET"})
     */
    public function show(Tva $tva): Response
    {
        return $this->render('tva/show.html.twig', [
            'tva' => $tva,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tva_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tva $tva): Response
    {
        $form = $this->createForm(TvaType::class, $tva);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tva_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tva/edit.html.twig', [
            'tva' => $tva,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="tva_delete", methods={"POST"})
     */
    public function delete(Request $request, Tva $tva): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tva->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tva);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tva_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tva/_delete_form.html.twig
<form method="post" action="{{ path('tva_delete', {'id': tva.id}) }}" onsubmit="return confirm('Vous êtes sur de vouloir supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tva.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/tva/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success m-1">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tva/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tva{% endblock %}

{% block body %}
    <div class="container">
    <h1 style="text-align: center">Modifier le Tva</h1>

    {{ include('tva/_form.html.twig', {'button_label': 'Mise a jour'}) }}

    <a class="btn mb-1 btn-secondary" href="{{ path('tva_index') }}">Retour a la liste</a>


    {{ include('tva/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/tva/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tva index{% endblock %}

{% block body %}
<div class="container">
  <h1 style="text-align: center">Taux-TVA</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Taux_tva</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tva in tvas %}
            <tr>
                <td>{{ tva.id }}</td>
                <td>{{ tva.tauxTva }}</td>
                <td>
                    <a class="btn mb-1 btn-success" href="{{ path('tva_show', {'id': tva.id}) }}">Voir</a>
                    <a class="btn mb-1 btn-primary" href="{{ path('tva_edit', {'id': tva.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tva_new') }}" class="btn btn-secondary">Creation nouveau</a>
</div>
  
{% endblock %}

templates/tva/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tva{% endblock %}

{% block body %}
<div class="container">
  <h1>Create new Tva</h1>

    {{ include('tva/_form.html.twig') }}

    <a href="{{ path('tva_index') }}">back to list</a>
</div>
  
{% endblock %}

templates/tva/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tva{% endblock %}

{% block body %}

    <div class="container">

    <h1 style="text-align: center">Tva</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tva.id }}</td>
            </tr>
            <tr>
                <th>Taux_tva</th>
                <td>{{ tva.tauxTva }}</td>
            </tr>
        </tbody>
    </table>

        <a class="btn mb-1 btn-secondary" href="{{ path('tva_index') }}">Retour a la liste</a>

        <a class="btn mb-1 btn-primary" href="{{ path('tva_edit', {'id': tva.id}) }}">Modifier</a>

    {{ include('tva/_delete_form.html.twig') }}

    </div>
{% endblock %}